title: Rich치rd P치vay # your name (or website title) here
logo: "/images/circle_photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <div>Data Analyst & Intelligence Professional</div>
  <br><br>
  I am a data analyst, with military intelligence background. My passion has always been to leverage information, which led me to fall in love with the world of data.
  <br><br>
  <b>Find me on:</b>
  <div><a href="/pdf/Rich치rd-P치vay-Resume.pdf" download>Resume</a></div>
  <div><a href="https://www.linkedin.com/in/rich%C3%A1rd-p%C3%A1vay/">LinkedIn</a></div>
  <div><a href="https://github.com/richardpavay">GitHub</a></div>
  <div><a href="https://public.tableau.com/app/profile/p.vay.rich.rd">Tableau Public</a></div>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
