title: Richárd Pávay # your name (or website title) here
logo: "/images/circle_photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <div>Data Analyst & Intelligence Professional</div>
  I am a data analyst, with military intelligence background in a NATO environment. My passion has always been to leverage information, which lead me to fall in love with the world of data, and how it “makes the world go around”.
  <b>Find me on:</b>
  <div><a href="https://www.linkedin.com/in/rich%C3%A1rd-p%C3%A1vay-378664260/">LinkedIn</a></div>
  <div><a href="https://github.com/richardpavay">GitHub</a></div>
  <div><a href="https://public.tableau.com/app/profile/p.vay.rich.rd">Tableau Public</a></div>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
